<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AuthenticationService.Domain\AuthenticationService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="MediatR" Version="12.4.1" />
      <PackageReference Include="Riok.Mapperly" Version="4.1.1" />
      <PackageReference Include="Voguedi.Utils.AutoMapper" Version="2.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="UseCases\Users\Commands\Delete\" />
      <Folder Include="UseCases\Users\Commands\Update\" />
      <Folder Include="UseCases\Users\Dtos\" />
      <Folder Include="UseCases\Users\Quaries\" />
    </ItemGroup>

</Project>
